import { defineStore } from 'pinia'

export const useNotificationStore = defineStore('notification', {
  state: () => ({
    notifications: [
      // 1. 최신 알림 (안 읽음)
      {
        id: 1,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '동승자 입장',
        content: '박지민님이 파티에 입장했습니다. 반갑게 인사해주세요!',
        time: '방금 전',
        isRead: false,
      },
      {
        id: 2,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '차량 도착 알림',
        content: '기사님이 픽업 장소에 도착했습니다. 3분 내로 탑승해주세요.',
        time: '2분 전',
        isRead: false,
      },
      {
        id: 3,
        type: 'event',
        categoryLabel: 'EVENT',
        title: '벚꽃 시즌 한정! 무료 탑승권',
        content: '지금 바로 쿠폰함을 확인하고 봄나들이 지원금을 받으세요.',
        time: '5분 전',
        isRead: false,
      },
      {
        id: 4,
        type: 'payment',
        categoryLabel: 'PAYMENT',
        title: '결제 실패 알림',
        content: '등록된 카드의 유효기간이 만료되었습니다. 결제 수단을 업데이트해주세요.',
        time: '10분 전',
        isRead: false,
      },
      {
        id: 5,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '매칭이 완료되었습니다!',
        content: '강남역 → 판교역 동승 매칭이 성공했습니다. 예상 소요시간은 45분입니다.',
        time: '15분 전',
        isRead: false,
      },

      // 2. 조금 지난 알림 (섞임)
      {
        id: 6,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '새로운 메시지',
        content: '김철수 기사님: "도착 예정 시간보다 5분 정도 늦을 것 같습니다."',
        time: '30분 전',
        isRead: true,
      },
      {
        id: 7,
        type: 'event',
        categoryLabel: 'EVENT',
        title: '친구 초대 이벤트 🎁',
        content: '친구를 초대하면 두 분 모두에게 5,000 포인트가 지급됩니다.',
        time: '1시간 전',
        isRead: false,
      },
      {
        id: 8,
        type: 'payment',
        categoryLabel: 'PAYMENT',
        title: '환불 완료',
        content: '취소하신 여정에 대한 수수료 1,500원이 환불되었습니다.',
        time: '3시간 전',
        isRead: true,
      },
      {
        id: 9,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '탑승 평가를 남겨주세요',
        content: '오늘 아침 등굣길 여정은 어떠셨나요? 별점을 남겨주세요.',
        time: '5시간 전',
        isRead: false,
      },
      {
        id: 10,
        type: 'payment',
        categoryLabel: 'PAYMENT',
        title: '정산이 완료되었습니다.',
        content: '어제 이용하신 여정의 요금 4,500원이 결제되었습니다.',
        time: '어제',
        isRead: true,
      },

      // 3. 과거 알림 (대부분 읽음)
      {
        id: 11,
        type: 'event',
        categoryLabel: 'EVENT',
        title: '비 오는 날 20% 할인 쿠폰',
        content: '오늘 같이 비 오는 날, 쾌적하게 이동하세요! 쿠폰이 발급되었습니다.',
        time: '어제',
        isRead: true,
      },
      {
        id: 12,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '예약 확정 안내',
        content: '내일(수) 오전 08:30 출근 카풀 예약이 확정되었습니다.',
        time: '2일 전',
        isRead: true,
      },
      {
        id: 13,
        type: 'payment',
        categoryLabel: 'PAYMENT',
        title: '포인트 충전 완료',
        content: '자동 충전 설정에 의해 50,000 포인트가 충전되었습니다.',
        time: '3일 전',
        isRead: true,
      },
      {
        id: 14,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '동승자 매칭 취소',
        content: '이영희님이 개인 사정으로 매칭을 취소했습니다. 새 동승자를 찾는 중입니다.',
        time: '3일 전',
        isRead: true,
      },
      {
        id: 15,
        type: 'event',
        categoryLabel: 'EVENT',
        title: 'VIP 등급 승급 안내',
        content: '축하합니다! 이번 달 탑승 횟수 달성으로 VIP 등급이 되셨습니다.',
        time: '4일 전',
        isRead: false, // 안 읽고 넘어간 옛날 알림
      },
      {
        id: 16,
        type: 'payment',
        categoryLabel: 'PAYMENT',
        title: '영수증 발급 안내',
        content: '요청하신 3월 이용 내역 영수증이 이메일로 발송되었습니다.',
        time: '5일 전',
        isRead: true,
      },
      {
        id: 17,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '하차 완료',
        content: '목적지에 도착했습니다. 잊으신 물건이 없는지 확인해주세요.',
        time: '1주일 전',
        isRead: true,
      },
      {
        id: 18,
        type: 'event',
        categoryLabel: 'EVENT',
        title: '서비스 점검 안내',
        content: '더 나은 서비스를 위해 새벽 2시부터 4시까지 점검이 진행됩니다.',
        time: '1주일 전',
        isRead: true,
      },
      {
        id: 19,
        type: 'payment',
        categoryLabel: 'PAYMENT',
        title: '카드 등록 완료',
        content: '새로운 결제 수단(신한카드)이 성공적으로 등록되었습니다.',
        time: '2주 전',
        isRead: true,
      },
      {
        id: 20,
        type: 'matching',
        categoryLabel: 'MATCHING',
        title: '회원가입을 축하합니다!',
        content: '서비스 이용을 환영합니다. 첫 탑승 시 사용 가능한 쿠폰을 드려요.',
        time: '1달 전',
        isRead: true,
      },
    ],
  }),
  actions: {
    markAllAsRead() {
      this.notifications.forEach((n) => (n.isRead = true))
    },
    markAsRead(id) {
      const item = this.notifications.find((n) => n.id === id)
      if (item) item.isRead = true
    },
  },
  persist: true,
})
